pipeline {
    agent any
    parameters {
    string(name: "Build_Number", defaultValue: "2", description: "Build number")

 }
    stages {
     stage ('download artifact') {
        steps{
            sh 'aws s3 cp s3://nouman-work/init_web_server.sh init_web_server.sh'
            sh "sed -i -e s/Var=.*/Var=my-app-1.0-SNAPSHOT.${params.Build_Number}.jar/g init_web_server.sh"
            sh 'aws s3 cp init_web_server.sh s3://nouman-work/init_web_server.sh'
        }
    }
     stage ('rotate autoscaling group') {
        steps{
            sh 'aws autoscaling start-instance-refresh --auto-scaling-group-name --region us-west-2 test-test-test-test-test-test-autoscaling-group'
        }
    }
  }
}

